//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maktaba
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssue
    {
        public string MemberId { get; set; }
        public string MemberName { get; set; }
        public string BookId { get; set; }
        public string BookName { get; set; }
        public string IssueDate { get; set; }
        public string Duedate { get; set; }
    }
}
