//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maktaba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookId { get; set; }
        public string BookName { get; set; }
        public string Genre { get; set; }
        public string AuthoName { get; set; }
        public string PublisherName { get; set; }
        public string PublishDate { get; set; }
        public Nullable<decimal> Language { get; set; }
        public string Edition { get; set; }
        public string BookCost { get; set; }
        public string NoofPages { get; set; }
        public string BookDesc { get; set; }
        public string ActualStock { get; set; }
        public string CurrentStock { get; set; }
        public string BookImgLink { get; set; }
    }
}
