//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maktaba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string FullName { get; set; }
        public string DOB { get; set; }
        public string Contacts { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string FullAddress { get; set; }
        public string MemberId { get; set; }
        public string Password { get; set; }
        public string AccStatus { get; set; }
    }
}
